version: "3"
services:
    mymongo:
        image: "mongo"

    myreader:
        build: .
        depends_on: 
            - mymongo
        ports:
            - "5001:5001"
        volumes:
            - datasets/
            - input/
            - out/
            - zip/